import './globals.css'
import { Inter } from 'next/font/google'

//components
import Allservices from '../components/Allservice'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tap Taxi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-slate-700" >
      <h1 className="text-red-800">This is home</h1>
        <Allservices className="text-red-800" />
        {children}
      </body>
    </html>
  )
}
